# Generated by Django 3.2 on 2021-11-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['name'], 'verbose_name': 'Director', 'verbose_name_plural': 'Directors'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ['gender'], 'verbose_name': 'Gender', 'verbose_name_plural': 'Genders'},
        ),
        migrations.AlterModelOptions(
            name='tv',
            options={'ordering': ['title'], 'verbose_name': 'Film', 'verbose_name_plural': 'Films'},
        ),
        migrations.AlterField(
            model_name='tv',
            name='director',
            field=models.ManyToManyField(related_name='rel_directors', to='tv.Director'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='gender',
            field=models.ManyToManyField(related_name='rel_genders', to='tv.Gender'),
        ),
    ]
