# Generated by Django 3.2 on 2021-11-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tvfinder'),
        ),
    ]
